# Exercise 2.B Cleaning up data

In [16]:
import numpy as np
import pandas as pd

In [17]:
df = pd.read_csv('df4_csv')
df

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [18]:
df.describe()

            ID       Age      Score
count  8.00000   6.00000   7.000000
mean   4.50000  25.00000  66.285714
std    2.44949   6.78233  32.576650
min    1.00000  18.00000  -1.000000
25%    2.75000  19.75000  60.000000
50%    4.50000  23.50000  78.000000
75%    6.25000  29.50000  87.500000
max    8.00000  35.00000  92.000000

## Filtering a DataFrame

In [21]:
df_age = df[df['Age'] > 18]

In [33]:
df_score = df[(df['Score'] > 50) & (df['Score'] < 100)]

In [52]:
df_age
df_score

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

## Modifying a DataFrame

In [59]:
df_cleaned = df.drop(df[df['Score'] < 0].index)
df_cleaned

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [66]:
df_cleaned.drop(columns=["City"])

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob   NaN   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace   NaN   55.0
7   8    Heidi  18.0   90.0

In [69]:
df_cleaned.fillna(df['Age'].mean())

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob  25.0         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston   25.0
6   7    Grace  25.0     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [75]:
df_cleaned.replace(np.nan, df['Score'].mean())

   ID     Name        Age       City      Score
0   1   Alicia  25.000000         NY  85.000000
1   2      Bob  66.285714         LA  92.000000
3   4  Dominic  19.000000    Houston  65.000000
4   5      Eve  31.000000    Phoenix  78.000000
5   6    Frank  35.000000     Boston  66.285714
6   7    Grace  66.285714     Austin  55.000000
7   8    Heidi  18.000000  San Diego  90.000000

In [76]:
df_cleaned.dropna()

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
7   8    Heidi  18.0  San Diego   90.0

In [82]:
df_cleaned.set_index('ID')
df_cleaned.drop(["ID"], axis = 1)
df_cleaned

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0